export const ADD_EDUCATION = 'ADD_EDUCATION'
export const EDIT_EDUCATION = 'EDIT_EDUCATION'
export const REMOVE_EDUCATION = 'REMOVE_EDUCATION'

export const ADD_EXPERIENCE = 'ADD_EXPERIENCE'
export const EDIT_EXPERIENCE = 'EDIT_EXPERIENCE'
export const REMOVE_EXPERIENCE = 'REMOVE_EXPERIENCE'

export const ADD_PROJECT = 'ADD_PROJECT'
export const EDIT_PROJECT = 'EDIT_PROJECT'
export const REMOVE_PROJECT = 'REMOVE_PROJECT'

export const EDIT_PERSONAL = 'EDIT_PERSONAL'

export const EDIT_SELECTED_TEMPLATE = 'EDIT_SELECTED_TEMPLATE'

export const ADD_SKILL = 'ADD_SKILL'
export const REMOVE_SKILL = 'REMOVE_SKILL'